<?php
// $Id$

function hvz_userpoints_hvz_player_killed($user, $killed) {
  $uid = $user->uid;
  if (hvz_get_status($uid)!=4) {
    userpoints_userpointsapi(array(
      'uid' => $user->uid,
      'points' => variable_get('hvz_userpoints_points', 5),
      'description' => l($user->name, 'user/' . $user->uid) .
               ' tagged ' . l($killed->name, 'user/' . $killed->uid) . '.',
      'tid' => variable_get('hvz_userpoints_tid', ''),
    )
    );
  }
}

function hvz_userpoints_hvz_oz_revealed($uid) {
  $user = user_load($uid);
  $query = db_query("SELECT * FROM {hvz} ORDER BY `killedtime` ASC");
  while ($victim = db_fetch_object($query)) {
    
    if ($victim->killedbyuid == $uid) {
      $victimuser = user_load($victim->uid);

      userpoints_userpointsapi(array(
        'uid' => $uid,
        'points' => variable_get('hvz_userpoints_points', 5),
        'description' => l($user->name, 'user/' . $uid) .
                 ' tagged ' . l($victimuser->name, 'user/' . $victim->uid) . ' as an OZ.',
        'tid' => variable_get('hvz_userpoints_tid', ''),
    )
    );
    }
  }
}

function hvz_userpoints_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'hvz_admin':
      $form['hvz_userpoints_set'] = array(
        '#type' => 'fieldset',
        '#title' => t('HvZ User Points'),
        '#description' => t('Userpoints for Humans vs Zombies'),
        '#collapsible' => TRUE,
        '#tree' => TRUE,
        '#weight' => 0,
      );

      $form['hvz_userpoints_set']['hvz_userpoints_points'] = array(
        '#type' => 'textfield',
        '#title' => t('Number of points per kill'),
        '#default_value' => variable_get('hvz_userpoints_points', 5),
        '#size' => 6,
        '#maxlength' => 6,
        '#required' => TRUE,
      );
      $form['hvz_userpoints_set']['hvz_userpoints_tid'] = array(
        '#type' => 'textfield',
        '#title' => t('Category ID'),
        '#default_value' => variable_get('hvz_userpoints_tid', ''),
        '#description' => 'The Taxonomy ID of the category you would like to give points to for zombie kills.',
        '#size' => 6,
        '#maxlength' => 6,
        '#weight' => 10,
      );
      $form['#validate'][] = 'hvz_userpoints_admin_validate';
      $form['#submit'][] = 'hvz_userpoints_admin_submit';
      break;
  }

}
function hvz_userpoints_admin_validate($form, &$form_state) {

}

function hvz_userpoints_admin_submit($form, &$form_state) {

  $points = $form_state['values']['hvz_userpoints_set']['hvz_userpoints_points'];
  $tid = $form_state['values']['hvz_userpoints_set']['hvz_userpoints_tid'];

  variable_set('hvz_userpoints_points', $points);
  variable_set('hvz_userpoints_tid', $tid);
}
